// <auto-generated />
namespace Lab_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editTableEmployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTableEmployee));
        
        string IMigrationMetadata.Id
        {
            get { return "202005180031042_editTableEmployee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
